/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as InitializeRouteImport } from './routes/initialize'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthConfirmEmailRouteImport } from './routes/_auth/confirm-email'
import { Route as AppOrganizationNameRouteRouteImport } from './routes/_app/$organizationName/route'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppMeIndexRouteImport } from './routes/_app/me/index'
import { Route as AppOrganizationNameIndexRouteImport } from './routes/_app/$organizationName/index'
import { Route as AppOrganizationsNewRouteImport } from './routes/_app/organizations/new'
import { Route as AppMePasswordRouteImport } from './routes/_app/me/password'
import { Route as AppMeNameRouteImport } from './routes/_app/me/name'
import { Route as AppMeInitializeRouteImport } from './routes/_app/me/initialize'
import { Route as AppMeIconRouteImport } from './routes/_app/me/icon'
import { Route as AppMeEmailRouteImport } from './routes/_app/me/email'
import { Route as AppMeDeleteRouteImport } from './routes/_app/me/delete'
import { Route as AppOrganizationNameMembersRouteRouteImport } from './routes/_app/$organizationName/members/route'
import { Route as AppOrganizationNameProjectsIndexRouteImport } from './routes/_app/$organizationName/projects/index'
import { Route as AppOrganizationNameMembersIndexRouteImport } from './routes/_app/$organizationName/members/index'
import { Route as AppOrganizationNameConfigurationIndexRouteImport } from './routes/_app/$organizationName/configuration/index'
import { Route as AppOrganizationNameActivitiesIndexRouteImport } from './routes/_app/$organizationName/activities/index'
import { Route as AppOrganizationNameProjectsNewRouteImport } from './routes/_app/$organizationName/projects/new'
import { Route as AppOrganizationNameMembersInviteRouteImport } from './routes/_app/$organizationName/members/invite'
import { Route as AppOrganizationNameConfigurationNameRouteImport } from './routes/_app/$organizationName/configuration/name'
import { Route as AppOrganizationNameConfigurationImportRouteImport } from './routes/_app/$organizationName/configuration/import'
import { Route as AppOrganizationNameConfigurationExportRouteImport } from './routes/_app/$organizationName/configuration/export'
import { Route as AppOrganizationNameConfigurationDisplayNameRouteImport } from './routes/_app/$organizationName/configuration/display-name'
import { Route as AppOrganizationNameConfigurationDeleteRouteImport } from './routes/_app/$organizationName/configuration/delete'
import { Route as AppOrganizationNameConfigurationActivitiesRouteImport } from './routes/_app/$organizationName/configuration/activities'
import { Route as AppOrganizationNameProjectsIdRouteRouteImport } from './routes/_app/$organizationName/projects/$id/route'
import { Route as AppOrganizationNameProjectsIdIndexRouteImport } from './routes/_app/$organizationName/projects/$id/index'
import { Route as AppOrganizationNameMembersMemberIdIndexRouteImport } from './routes/_app/$organizationName/members/$memberId/index'
import { Route as AppOrganizationNameProjectsIdConfigurationsRouteImport } from './routes/_app/$organizationName/projects/$id/configurations'
import { Route as AppOrganizationNameMembersMemberIdRoleRouteImport } from './routes/_app/$organizationName/members/$memberId/role'
import { Route as AppOrganizationNameProjectsIdSettingsIndexRouteImport } from './routes/_app/$organizationName/projects/$id/settings/index'
import { Route as AppOrganizationNameProjectsIdSettingsNameRouteImport } from './routes/_app/$organizationName/projects/$id/settings/name'
import { Route as AppOrganizationNameProjectsIdSettingsDescriptionRouteImport } from './routes/_app/$organizationName/projects/$id/settings/description'
import { Route as AppOrganizationNameProjectsIdSettingsDeleteRouteImport } from './routes/_app/$organizationName/projects/$id/settings/delete'
import { Route as AppOrganizationNameProjectsIdSettingsActivitiesRouteImport } from './routes/_app/$organizationName/projects/$id/settings/activities'
import { Route as AppOrganizationNameProjectsIdMembersMemberIdRouteRouteImport } from './routes/_app/$organizationName/projects/$id/members/$memberId/route'
import { Route as AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRouteImport } from './routes/_app/$organizationName/projects/$id/members/$memberId/assignments'
import { Route as AppOrganizationNameProjectsIdMembersMemberIdActivitiesRouteImport } from './routes/_app/$organizationName/projects/$id/members/$memberId/activities'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRoute = InitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppOrganizationNameRouteRoute =
  AppOrganizationNameRouteRouteImport.update({
    id: '/$organizationName',
    path: '/$organizationName',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIndexRoute = AppMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationNameIndexRoute =
  AppOrganizationNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationsNewRoute = AppOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMePasswordRoute = AppMePasswordRouteImport.update({
  id: '/me/password',
  path: '/me/password',
  getParentRoute: () => AppRoute,
} as any)
const AppMeNameRoute = AppMeNameRouteImport.update({
  id: '/me/name',
  path: '/me/name',
  getParentRoute: () => AppRoute,
} as any)
const AppMeInitializeRoute = AppMeInitializeRouteImport.update({
  id: '/me/initialize',
  path: '/me/initialize',
  getParentRoute: () => AppRoute,
} as any)
const AppMeIconRoute = AppMeIconRouteImport.update({
  id: '/me/icon',
  path: '/me/icon',
  getParentRoute: () => AppRoute,
} as any)
const AppMeEmailRoute = AppMeEmailRouteImport.update({
  id: '/me/email',
  path: '/me/email',
  getParentRoute: () => AppRoute,
} as any)
const AppMeDeleteRoute = AppMeDeleteRouteImport.update({
  id: '/me/delete',
  path: '/me/delete',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationNameMembersRouteRoute =
  AppOrganizationNameMembersRouteRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameProjectsIndexRoute =
  AppOrganizationNameProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameMembersIndexRoute =
  AppOrganizationNameMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationNameMembersRouteRoute,
  } as any)
const AppOrganizationNameConfigurationIndexRoute =
  AppOrganizationNameConfigurationIndexRouteImport.update({
    id: '/configuration/',
    path: '/configuration/',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameActivitiesIndexRoute =
  AppOrganizationNameActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameProjectsNewRoute =
  AppOrganizationNameProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameMembersInviteRoute =
  AppOrganizationNameMembersInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AppOrganizationNameMembersRouteRoute,
  } as any)
const AppOrganizationNameConfigurationNameRoute =
  AppOrganizationNameConfigurationNameRouteImport.update({
    id: '/configuration/name',
    path: '/configuration/name',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameConfigurationImportRoute =
  AppOrganizationNameConfigurationImportRouteImport.update({
    id: '/configuration/import',
    path: '/configuration/import',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameConfigurationExportRoute =
  AppOrganizationNameConfigurationExportRouteImport.update({
    id: '/configuration/export',
    path: '/configuration/export',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameConfigurationDisplayNameRoute =
  AppOrganizationNameConfigurationDisplayNameRouteImport.update({
    id: '/configuration/display-name',
    path: '/configuration/display-name',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameConfigurationDeleteRoute =
  AppOrganizationNameConfigurationDeleteRouteImport.update({
    id: '/configuration/delete',
    path: '/configuration/delete',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameConfigurationActivitiesRoute =
  AppOrganizationNameConfigurationActivitiesRouteImport.update({
    id: '/configuration/activities',
    path: '/configuration/activities',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdRouteRoute =
  AppOrganizationNameProjectsIdRouteRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AppOrganizationNameRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdIndexRoute =
  AppOrganizationNameProjectsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameMembersMemberIdIndexRoute =
  AppOrganizationNameMembersMemberIdIndexRouteImport.update({
    id: '/$memberId/',
    path: '/$memberId/',
    getParentRoute: () => AppOrganizationNameMembersRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdConfigurationsRoute =
  AppOrganizationNameProjectsIdConfigurationsRouteImport.update({
    id: '/configurations',
    path: '/configurations',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameMembersMemberIdRoleRoute =
  AppOrganizationNameMembersMemberIdRoleRouteImport.update({
    id: '/$memberId/role',
    path: '/$memberId/role',
    getParentRoute: () => AppOrganizationNameMembersRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdSettingsIndexRoute =
  AppOrganizationNameProjectsIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdSettingsNameRoute =
  AppOrganizationNameProjectsIdSettingsNameRouteImport.update({
    id: '/settings/name',
    path: '/settings/name',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdSettingsDescriptionRoute =
  AppOrganizationNameProjectsIdSettingsDescriptionRouteImport.update({
    id: '/settings/description',
    path: '/settings/description',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdSettingsDeleteRoute =
  AppOrganizationNameProjectsIdSettingsDeleteRouteImport.update({
    id: '/settings/delete',
    path: '/settings/delete',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdSettingsActivitiesRoute =
  AppOrganizationNameProjectsIdSettingsActivitiesRouteImport.update({
    id: '/settings/activities',
    path: '/settings/activities',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdMembersMemberIdRouteRoute =
  AppOrganizationNameProjectsIdMembersMemberIdRouteRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AppOrganizationNameProjectsIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute =
  AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () =>
      AppOrganizationNameProjectsIdMembersMemberIdRouteRoute,
  } as any)
const AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute =
  AppOrganizationNameProjectsIdMembersMemberIdActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () =>
      AppOrganizationNameProjectsIdMembersMemberIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/initialize': typeof InitializeRoute
  '/update-password': typeof UpdatePasswordRoute
  '/$organizationName': typeof AppOrganizationNameRouteRouteWithChildren
  '/confirm-email': typeof AuthConfirmEmailRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/$organizationName/members': typeof AppOrganizationNameMembersRouteRouteWithChildren
  '/me/delete': typeof AppMeDeleteRoute
  '/me/email': typeof AppMeEmailRoute
  '/me/icon': typeof AppMeIconRoute
  '/me/initialize': typeof AppMeInitializeRoute
  '/me/name': typeof AppMeNameRoute
  '/me/password': typeof AppMePasswordRoute
  '/organizations/new': typeof AppOrganizationsNewRoute
  '/$organizationName/': typeof AppOrganizationNameIndexRoute
  '/me/': typeof AppMeIndexRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/$organizationName/projects/$id': typeof AppOrganizationNameProjectsIdRouteRouteWithChildren
  '/$organizationName/configuration/activities': typeof AppOrganizationNameConfigurationActivitiesRoute
  '/$organizationName/configuration/delete': typeof AppOrganizationNameConfigurationDeleteRoute
  '/$organizationName/configuration/display-name': typeof AppOrganizationNameConfigurationDisplayNameRoute
  '/$organizationName/configuration/export': typeof AppOrganizationNameConfigurationExportRoute
  '/$organizationName/configuration/import': typeof AppOrganizationNameConfigurationImportRoute
  '/$organizationName/configuration/name': typeof AppOrganizationNameConfigurationNameRoute
  '/$organizationName/members/invite': typeof AppOrganizationNameMembersInviteRoute
  '/$organizationName/projects/new': typeof AppOrganizationNameProjectsNewRoute
  '/$organizationName/activities/': typeof AppOrganizationNameActivitiesIndexRoute
  '/$organizationName/configuration/': typeof AppOrganizationNameConfigurationIndexRoute
  '/$organizationName/members/': typeof AppOrganizationNameMembersIndexRoute
  '/$organizationName/projects/': typeof AppOrganizationNameProjectsIndexRoute
  '/$organizationName/members/$memberId/role': typeof AppOrganizationNameMembersMemberIdRoleRoute
  '/$organizationName/projects/$id/configurations': typeof AppOrganizationNameProjectsIdConfigurationsRoute
  '/$organizationName/members/$memberId/': typeof AppOrganizationNameMembersMemberIdIndexRoute
  '/$organizationName/projects/$id/': typeof AppOrganizationNameProjectsIdIndexRoute
  '/$organizationName/projects/$id/members/$memberId': typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRouteWithChildren
  '/$organizationName/projects/$id/settings/activities': typeof AppOrganizationNameProjectsIdSettingsActivitiesRoute
  '/$organizationName/projects/$id/settings/delete': typeof AppOrganizationNameProjectsIdSettingsDeleteRoute
  '/$organizationName/projects/$id/settings/description': typeof AppOrganizationNameProjectsIdSettingsDescriptionRoute
  '/$organizationName/projects/$id/settings/name': typeof AppOrganizationNameProjectsIdSettingsNameRoute
  '/$organizationName/projects/$id/settings/': typeof AppOrganizationNameProjectsIdSettingsIndexRoute
  '/$organizationName/projects/$id/members/$memberId/activities': typeof AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute
  '/$organizationName/projects/$id/members/$memberId/assignments': typeof AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/initialize': typeof InitializeRoute
  '/update-password': typeof UpdatePasswordRoute
  '/confirm-email': typeof AuthConfirmEmailRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/me/delete': typeof AppMeDeleteRoute
  '/me/email': typeof AppMeEmailRoute
  '/me/icon': typeof AppMeIconRoute
  '/me/initialize': typeof AppMeInitializeRoute
  '/me/name': typeof AppMeNameRoute
  '/me/password': typeof AppMePasswordRoute
  '/organizations/new': typeof AppOrganizationsNewRoute
  '/$organizationName': typeof AppOrganizationNameIndexRoute
  '/me': typeof AppMeIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/$organizationName/configuration/activities': typeof AppOrganizationNameConfigurationActivitiesRoute
  '/$organizationName/configuration/delete': typeof AppOrganizationNameConfigurationDeleteRoute
  '/$organizationName/configuration/display-name': typeof AppOrganizationNameConfigurationDisplayNameRoute
  '/$organizationName/configuration/export': typeof AppOrganizationNameConfigurationExportRoute
  '/$organizationName/configuration/import': typeof AppOrganizationNameConfigurationImportRoute
  '/$organizationName/configuration/name': typeof AppOrganizationNameConfigurationNameRoute
  '/$organizationName/members/invite': typeof AppOrganizationNameMembersInviteRoute
  '/$organizationName/projects/new': typeof AppOrganizationNameProjectsNewRoute
  '/$organizationName/activities': typeof AppOrganizationNameActivitiesIndexRoute
  '/$organizationName/configuration': typeof AppOrganizationNameConfigurationIndexRoute
  '/$organizationName/members': typeof AppOrganizationNameMembersIndexRoute
  '/$organizationName/projects': typeof AppOrganizationNameProjectsIndexRoute
  '/$organizationName/members/$memberId/role': typeof AppOrganizationNameMembersMemberIdRoleRoute
  '/$organizationName/projects/$id/configurations': typeof AppOrganizationNameProjectsIdConfigurationsRoute
  '/$organizationName/members/$memberId': typeof AppOrganizationNameMembersMemberIdIndexRoute
  '/$organizationName/projects/$id': typeof AppOrganizationNameProjectsIdIndexRoute
  '/$organizationName/projects/$id/members/$memberId': typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRouteWithChildren
  '/$organizationName/projects/$id/settings/activities': typeof AppOrganizationNameProjectsIdSettingsActivitiesRoute
  '/$organizationName/projects/$id/settings/delete': typeof AppOrganizationNameProjectsIdSettingsDeleteRoute
  '/$organizationName/projects/$id/settings/description': typeof AppOrganizationNameProjectsIdSettingsDescriptionRoute
  '/$organizationName/projects/$id/settings/name': typeof AppOrganizationNameProjectsIdSettingsNameRoute
  '/$organizationName/projects/$id/settings': typeof AppOrganizationNameProjectsIdSettingsIndexRoute
  '/$organizationName/projects/$id/members/$memberId/activities': typeof AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute
  '/$organizationName/projects/$id/members/$memberId/assignments': typeof AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/initialize': typeof InitializeRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_app/$organizationName': typeof AppOrganizationNameRouteRouteWithChildren
  '/_auth/confirm-email': typeof AuthConfirmEmailRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$organizationName/members': typeof AppOrganizationNameMembersRouteRouteWithChildren
  '/_app/me/delete': typeof AppMeDeleteRoute
  '/_app/me/email': typeof AppMeEmailRoute
  '/_app/me/icon': typeof AppMeIconRoute
  '/_app/me/initialize': typeof AppMeInitializeRoute
  '/_app/me/name': typeof AppMeNameRoute
  '/_app/me/password': typeof AppMePasswordRoute
  '/_app/organizations/new': typeof AppOrganizationsNewRoute
  '/_app/$organizationName/': typeof AppOrganizationNameIndexRoute
  '/_app/me/': typeof AppMeIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/$organizationName/projects/$id': typeof AppOrganizationNameProjectsIdRouteRouteWithChildren
  '/_app/$organizationName/configuration/activities': typeof AppOrganizationNameConfigurationActivitiesRoute
  '/_app/$organizationName/configuration/delete': typeof AppOrganizationNameConfigurationDeleteRoute
  '/_app/$organizationName/configuration/display-name': typeof AppOrganizationNameConfigurationDisplayNameRoute
  '/_app/$organizationName/configuration/export': typeof AppOrganizationNameConfigurationExportRoute
  '/_app/$organizationName/configuration/import': typeof AppOrganizationNameConfigurationImportRoute
  '/_app/$organizationName/configuration/name': typeof AppOrganizationNameConfigurationNameRoute
  '/_app/$organizationName/members/invite': typeof AppOrganizationNameMembersInviteRoute
  '/_app/$organizationName/projects/new': typeof AppOrganizationNameProjectsNewRoute
  '/_app/$organizationName/activities/': typeof AppOrganizationNameActivitiesIndexRoute
  '/_app/$organizationName/configuration/': typeof AppOrganizationNameConfigurationIndexRoute
  '/_app/$organizationName/members/': typeof AppOrganizationNameMembersIndexRoute
  '/_app/$organizationName/projects/': typeof AppOrganizationNameProjectsIndexRoute
  '/_app/$organizationName/members/$memberId/role': typeof AppOrganizationNameMembersMemberIdRoleRoute
  '/_app/$organizationName/projects/$id/configurations': typeof AppOrganizationNameProjectsIdConfigurationsRoute
  '/_app/$organizationName/members/$memberId/': typeof AppOrganizationNameMembersMemberIdIndexRoute
  '/_app/$organizationName/projects/$id/': typeof AppOrganizationNameProjectsIdIndexRoute
  '/_app/$organizationName/projects/$id/members/$memberId': typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRouteWithChildren
  '/_app/$organizationName/projects/$id/settings/activities': typeof AppOrganizationNameProjectsIdSettingsActivitiesRoute
  '/_app/$organizationName/projects/$id/settings/delete': typeof AppOrganizationNameProjectsIdSettingsDeleteRoute
  '/_app/$organizationName/projects/$id/settings/description': typeof AppOrganizationNameProjectsIdSettingsDescriptionRoute
  '/_app/$organizationName/projects/$id/settings/name': typeof AppOrganizationNameProjectsIdSettingsNameRoute
  '/_app/$organizationName/projects/$id/settings/': typeof AppOrganizationNameProjectsIdSettingsIndexRoute
  '/_app/$organizationName/projects/$id/members/$memberId/activities': typeof AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute
  '/_app/$organizationName/projects/$id/members/$memberId/assignments': typeof AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/initialize'
    | '/update-password'
    | '/$organizationName'
    | '/confirm-email'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$organizationName/members'
    | '/me/delete'
    | '/me/email'
    | '/me/icon'
    | '/me/initialize'
    | '/me/name'
    | '/me/password'
    | '/organizations/new'
    | '/$organizationName/'
    | '/me/'
    | '/organizations/'
    | '/$organizationName/projects/$id'
    | '/$organizationName/configuration/activities'
    | '/$organizationName/configuration/delete'
    | '/$organizationName/configuration/display-name'
    | '/$organizationName/configuration/export'
    | '/$organizationName/configuration/import'
    | '/$organizationName/configuration/name'
    | '/$organizationName/members/invite'
    | '/$organizationName/projects/new'
    | '/$organizationName/activities/'
    | '/$organizationName/configuration/'
    | '/$organizationName/members/'
    | '/$organizationName/projects/'
    | '/$organizationName/members/$memberId/role'
    | '/$organizationName/projects/$id/configurations'
    | '/$organizationName/members/$memberId/'
    | '/$organizationName/projects/$id/'
    | '/$organizationName/projects/$id/members/$memberId'
    | '/$organizationName/projects/$id/settings/activities'
    | '/$organizationName/projects/$id/settings/delete'
    | '/$organizationName/projects/$id/settings/description'
    | '/$organizationName/projects/$id/settings/name'
    | '/$organizationName/projects/$id/settings/'
    | '/$organizationName/projects/$id/members/$memberId/activities'
    | '/$organizationName/projects/$id/members/$memberId/assignments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/initialize'
    | '/update-password'
    | '/confirm-email'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/me/delete'
    | '/me/email'
    | '/me/icon'
    | '/me/initialize'
    | '/me/name'
    | '/me/password'
    | '/organizations/new'
    | '/$organizationName'
    | '/me'
    | '/organizations'
    | '/$organizationName/configuration/activities'
    | '/$organizationName/configuration/delete'
    | '/$organizationName/configuration/display-name'
    | '/$organizationName/configuration/export'
    | '/$organizationName/configuration/import'
    | '/$organizationName/configuration/name'
    | '/$organizationName/members/invite'
    | '/$organizationName/projects/new'
    | '/$organizationName/activities'
    | '/$organizationName/configuration'
    | '/$organizationName/members'
    | '/$organizationName/projects'
    | '/$organizationName/members/$memberId/role'
    | '/$organizationName/projects/$id/configurations'
    | '/$organizationName/members/$memberId'
    | '/$organizationName/projects/$id'
    | '/$organizationName/projects/$id/members/$memberId'
    | '/$organizationName/projects/$id/settings/activities'
    | '/$organizationName/projects/$id/settings/delete'
    | '/$organizationName/projects/$id/settings/description'
    | '/$organizationName/projects/$id/settings/name'
    | '/$organizationName/projects/$id/settings'
    | '/$organizationName/projects/$id/members/$memberId/activities'
    | '/$organizationName/projects/$id/members/$memberId/assignments'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/initialize'
    | '/update-password'
    | '/_app/$organizationName'
    | '/_auth/confirm-email'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/$organizationName/members'
    | '/_app/me/delete'
    | '/_app/me/email'
    | '/_app/me/icon'
    | '/_app/me/initialize'
    | '/_app/me/name'
    | '/_app/me/password'
    | '/_app/organizations/new'
    | '/_app/$organizationName/'
    | '/_app/me/'
    | '/_app/organizations/'
    | '/_app/$organizationName/projects/$id'
    | '/_app/$organizationName/configuration/activities'
    | '/_app/$organizationName/configuration/delete'
    | '/_app/$organizationName/configuration/display-name'
    | '/_app/$organizationName/configuration/export'
    | '/_app/$organizationName/configuration/import'
    | '/_app/$organizationName/configuration/name'
    | '/_app/$organizationName/members/invite'
    | '/_app/$organizationName/projects/new'
    | '/_app/$organizationName/activities/'
    | '/_app/$organizationName/configuration/'
    | '/_app/$organizationName/members/'
    | '/_app/$organizationName/projects/'
    | '/_app/$organizationName/members/$memberId/role'
    | '/_app/$organizationName/projects/$id/configurations'
    | '/_app/$organizationName/members/$memberId/'
    | '/_app/$organizationName/projects/$id/'
    | '/_app/$organizationName/projects/$id/members/$memberId'
    | '/_app/$organizationName/projects/$id/settings/activities'
    | '/_app/$organizationName/projects/$id/settings/delete'
    | '/_app/$organizationName/projects/$id/settings/description'
    | '/_app/$organizationName/projects/$id/settings/name'
    | '/_app/$organizationName/projects/$id/settings/'
    | '/_app/$organizationName/projects/$id/members/$memberId/activities'
    | '/_app/$organizationName/projects/$id/members/$memberId/assignments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InitializeRoute: typeof InitializeRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirm-email': {
      id: '/_auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/$organizationName': {
      id: '/_app/$organizationName'
      path: '/$organizationName'
      fullPath: '/$organizationName'
      preLoaderRoute: typeof AppOrganizationNameRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/': {
      id: '/_app/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AppMeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organizationName/': {
      id: '/_app/$organizationName/'
      path: '/'
      fullPath: '/$organizationName/'
      preLoaderRoute: typeof AppOrganizationNameIndexRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/organizations/new': {
      id: '/_app/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AppOrganizationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/password': {
      id: '/_app/me/password'
      path: '/me/password'
      fullPath: '/me/password'
      preLoaderRoute: typeof AppMePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/name': {
      id: '/_app/me/name'
      path: '/me/name'
      fullPath: '/me/name'
      preLoaderRoute: typeof AppMeNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/initialize': {
      id: '/_app/me/initialize'
      path: '/me/initialize'
      fullPath: '/me/initialize'
      preLoaderRoute: typeof AppMeInitializeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/icon': {
      id: '/_app/me/icon'
      path: '/me/icon'
      fullPath: '/me/icon'
      preLoaderRoute: typeof AppMeIconRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/email': {
      id: '/_app/me/email'
      path: '/me/email'
      fullPath: '/me/email'
      preLoaderRoute: typeof AppMeEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me/delete': {
      id: '/_app/me/delete'
      path: '/me/delete'
      fullPath: '/me/delete'
      preLoaderRoute: typeof AppMeDeleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organizationName/members': {
      id: '/_app/$organizationName/members'
      path: '/members'
      fullPath: '/$organizationName/members'
      preLoaderRoute: typeof AppOrganizationNameMembersRouteRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/projects/': {
      id: '/_app/$organizationName/projects/'
      path: '/projects'
      fullPath: '/$organizationName/projects/'
      preLoaderRoute: typeof AppOrganizationNameProjectsIndexRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/members/': {
      id: '/_app/$organizationName/members/'
      path: '/'
      fullPath: '/$organizationName/members/'
      preLoaderRoute: typeof AppOrganizationNameMembersIndexRouteImport
      parentRoute: typeof AppOrganizationNameMembersRouteRoute
    }
    '/_app/$organizationName/configuration/': {
      id: '/_app/$organizationName/configuration/'
      path: '/configuration'
      fullPath: '/$organizationName/configuration/'
      preLoaderRoute: typeof AppOrganizationNameConfigurationIndexRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/activities/': {
      id: '/_app/$organizationName/activities/'
      path: '/activities'
      fullPath: '/$organizationName/activities/'
      preLoaderRoute: typeof AppOrganizationNameActivitiesIndexRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/projects/new': {
      id: '/_app/$organizationName/projects/new'
      path: '/projects/new'
      fullPath: '/$organizationName/projects/new'
      preLoaderRoute: typeof AppOrganizationNameProjectsNewRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/members/invite': {
      id: '/_app/$organizationName/members/invite'
      path: '/invite'
      fullPath: '/$organizationName/members/invite'
      preLoaderRoute: typeof AppOrganizationNameMembersInviteRouteImport
      parentRoute: typeof AppOrganizationNameMembersRouteRoute
    }
    '/_app/$organizationName/configuration/name': {
      id: '/_app/$organizationName/configuration/name'
      path: '/configuration/name'
      fullPath: '/$organizationName/configuration/name'
      preLoaderRoute: typeof AppOrganizationNameConfigurationNameRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/configuration/import': {
      id: '/_app/$organizationName/configuration/import'
      path: '/configuration/import'
      fullPath: '/$organizationName/configuration/import'
      preLoaderRoute: typeof AppOrganizationNameConfigurationImportRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/configuration/export': {
      id: '/_app/$organizationName/configuration/export'
      path: '/configuration/export'
      fullPath: '/$organizationName/configuration/export'
      preLoaderRoute: typeof AppOrganizationNameConfigurationExportRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/configuration/display-name': {
      id: '/_app/$organizationName/configuration/display-name'
      path: '/configuration/display-name'
      fullPath: '/$organizationName/configuration/display-name'
      preLoaderRoute: typeof AppOrganizationNameConfigurationDisplayNameRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/configuration/delete': {
      id: '/_app/$organizationName/configuration/delete'
      path: '/configuration/delete'
      fullPath: '/$organizationName/configuration/delete'
      preLoaderRoute: typeof AppOrganizationNameConfigurationDeleteRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/configuration/activities': {
      id: '/_app/$organizationName/configuration/activities'
      path: '/configuration/activities'
      fullPath: '/$organizationName/configuration/activities'
      preLoaderRoute: typeof AppOrganizationNameConfigurationActivitiesRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/projects/$id': {
      id: '/_app/$organizationName/projects/$id'
      path: '/projects/$id'
      fullPath: '/$organizationName/projects/$id'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdRouteRouteImport
      parentRoute: typeof AppOrganizationNameRouteRoute
    }
    '/_app/$organizationName/projects/$id/': {
      id: '/_app/$organizationName/projects/$id/'
      path: '/'
      fullPath: '/$organizationName/projects/$id/'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdIndexRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/members/$memberId/': {
      id: '/_app/$organizationName/members/$memberId/'
      path: '/$memberId'
      fullPath: '/$organizationName/members/$memberId/'
      preLoaderRoute: typeof AppOrganizationNameMembersMemberIdIndexRouteImport
      parentRoute: typeof AppOrganizationNameMembersRouteRoute
    }
    '/_app/$organizationName/projects/$id/configurations': {
      id: '/_app/$organizationName/projects/$id/configurations'
      path: '/configurations'
      fullPath: '/$organizationName/projects/$id/configurations'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdConfigurationsRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/members/$memberId/role': {
      id: '/_app/$organizationName/members/$memberId/role'
      path: '/$memberId/role'
      fullPath: '/$organizationName/members/$memberId/role'
      preLoaderRoute: typeof AppOrganizationNameMembersMemberIdRoleRouteImport
      parentRoute: typeof AppOrganizationNameMembersRouteRoute
    }
    '/_app/$organizationName/projects/$id/settings/': {
      id: '/_app/$organizationName/projects/$id/settings/'
      path: '/settings'
      fullPath: '/$organizationName/projects/$id/settings/'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdSettingsIndexRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/settings/name': {
      id: '/_app/$organizationName/projects/$id/settings/name'
      path: '/settings/name'
      fullPath: '/$organizationName/projects/$id/settings/name'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdSettingsNameRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/settings/description': {
      id: '/_app/$organizationName/projects/$id/settings/description'
      path: '/settings/description'
      fullPath: '/$organizationName/projects/$id/settings/description'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdSettingsDescriptionRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/settings/delete': {
      id: '/_app/$organizationName/projects/$id/settings/delete'
      path: '/settings/delete'
      fullPath: '/$organizationName/projects/$id/settings/delete'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdSettingsDeleteRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/settings/activities': {
      id: '/_app/$organizationName/projects/$id/settings/activities'
      path: '/settings/activities'
      fullPath: '/$organizationName/projects/$id/settings/activities'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdSettingsActivitiesRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/members/$memberId': {
      id: '/_app/$organizationName/projects/$id/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/$organizationName/projects/$id/members/$memberId'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/members/$memberId/assignments': {
      id: '/_app/$organizationName/projects/$id/members/$memberId/assignments'
      path: '/assignments'
      fullPath: '/$organizationName/projects/$id/members/$memberId/assignments'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRoute
    }
    '/_app/$organizationName/projects/$id/members/$memberId/activities': {
      id: '/_app/$organizationName/projects/$id/members/$memberId/activities'
      path: '/activities'
      fullPath: '/$organizationName/projects/$id/members/$memberId/activities'
      preLoaderRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdActivitiesRouteImport
      parentRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRoute
    }
  }
}

interface AppOrganizationNameMembersRouteRouteChildren {
  AppOrganizationNameMembersInviteRoute: typeof AppOrganizationNameMembersInviteRoute
  AppOrganizationNameMembersIndexRoute: typeof AppOrganizationNameMembersIndexRoute
  AppOrganizationNameMembersMemberIdRoleRoute: typeof AppOrganizationNameMembersMemberIdRoleRoute
  AppOrganizationNameMembersMemberIdIndexRoute: typeof AppOrganizationNameMembersMemberIdIndexRoute
}

const AppOrganizationNameMembersRouteRouteChildren: AppOrganizationNameMembersRouteRouteChildren =
  {
    AppOrganizationNameMembersInviteRoute:
      AppOrganizationNameMembersInviteRoute,
    AppOrganizationNameMembersIndexRoute: AppOrganizationNameMembersIndexRoute,
    AppOrganizationNameMembersMemberIdRoleRoute:
      AppOrganizationNameMembersMemberIdRoleRoute,
    AppOrganizationNameMembersMemberIdIndexRoute:
      AppOrganizationNameMembersMemberIdIndexRoute,
  }

const AppOrganizationNameMembersRouteRouteWithChildren =
  AppOrganizationNameMembersRouteRoute._addFileChildren(
    AppOrganizationNameMembersRouteRouteChildren,
  )

interface AppOrganizationNameProjectsIdMembersMemberIdRouteRouteChildren {
  AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute
  AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute
}

const AppOrganizationNameProjectsIdMembersMemberIdRouteRouteChildren: AppOrganizationNameProjectsIdMembersMemberIdRouteRouteChildren =
  {
    AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute:
      AppOrganizationNameProjectsIdMembersMemberIdActivitiesRoute,
    AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute:
      AppOrganizationNameProjectsIdMembersMemberIdAssignmentsRoute,
  }

const AppOrganizationNameProjectsIdMembersMemberIdRouteRouteWithChildren =
  AppOrganizationNameProjectsIdMembersMemberIdRouteRoute._addFileChildren(
    AppOrganizationNameProjectsIdMembersMemberIdRouteRouteChildren,
  )

interface AppOrganizationNameProjectsIdRouteRouteChildren {
  AppOrganizationNameProjectsIdConfigurationsRoute: typeof AppOrganizationNameProjectsIdConfigurationsRoute
  AppOrganizationNameProjectsIdIndexRoute: typeof AppOrganizationNameProjectsIdIndexRoute
  AppOrganizationNameProjectsIdMembersMemberIdRouteRoute: typeof AppOrganizationNameProjectsIdMembersMemberIdRouteRouteWithChildren
  AppOrganizationNameProjectsIdSettingsActivitiesRoute: typeof AppOrganizationNameProjectsIdSettingsActivitiesRoute
  AppOrganizationNameProjectsIdSettingsDeleteRoute: typeof AppOrganizationNameProjectsIdSettingsDeleteRoute
  AppOrganizationNameProjectsIdSettingsDescriptionRoute: typeof AppOrganizationNameProjectsIdSettingsDescriptionRoute
  AppOrganizationNameProjectsIdSettingsNameRoute: typeof AppOrganizationNameProjectsIdSettingsNameRoute
  AppOrganizationNameProjectsIdSettingsIndexRoute: typeof AppOrganizationNameProjectsIdSettingsIndexRoute
}

const AppOrganizationNameProjectsIdRouteRouteChildren: AppOrganizationNameProjectsIdRouteRouteChildren =
  {
    AppOrganizationNameProjectsIdConfigurationsRoute:
      AppOrganizationNameProjectsIdConfigurationsRoute,
    AppOrganizationNameProjectsIdIndexRoute:
      AppOrganizationNameProjectsIdIndexRoute,
    AppOrganizationNameProjectsIdMembersMemberIdRouteRoute:
      AppOrganizationNameProjectsIdMembersMemberIdRouteRouteWithChildren,
    AppOrganizationNameProjectsIdSettingsActivitiesRoute:
      AppOrganizationNameProjectsIdSettingsActivitiesRoute,
    AppOrganizationNameProjectsIdSettingsDeleteRoute:
      AppOrganizationNameProjectsIdSettingsDeleteRoute,
    AppOrganizationNameProjectsIdSettingsDescriptionRoute:
      AppOrganizationNameProjectsIdSettingsDescriptionRoute,
    AppOrganizationNameProjectsIdSettingsNameRoute:
      AppOrganizationNameProjectsIdSettingsNameRoute,
    AppOrganizationNameProjectsIdSettingsIndexRoute:
      AppOrganizationNameProjectsIdSettingsIndexRoute,
  }

const AppOrganizationNameProjectsIdRouteRouteWithChildren =
  AppOrganizationNameProjectsIdRouteRoute._addFileChildren(
    AppOrganizationNameProjectsIdRouteRouteChildren,
  )

interface AppOrganizationNameRouteRouteChildren {
  AppOrganizationNameMembersRouteRoute: typeof AppOrganizationNameMembersRouteRouteWithChildren
  AppOrganizationNameIndexRoute: typeof AppOrganizationNameIndexRoute
  AppOrganizationNameProjectsIdRouteRoute: typeof AppOrganizationNameProjectsIdRouteRouteWithChildren
  AppOrganizationNameConfigurationActivitiesRoute: typeof AppOrganizationNameConfigurationActivitiesRoute
  AppOrganizationNameConfigurationDeleteRoute: typeof AppOrganizationNameConfigurationDeleteRoute
  AppOrganizationNameConfigurationDisplayNameRoute: typeof AppOrganizationNameConfigurationDisplayNameRoute
  AppOrganizationNameConfigurationExportRoute: typeof AppOrganizationNameConfigurationExportRoute
  AppOrganizationNameConfigurationImportRoute: typeof AppOrganizationNameConfigurationImportRoute
  AppOrganizationNameConfigurationNameRoute: typeof AppOrganizationNameConfigurationNameRoute
  AppOrganizationNameProjectsNewRoute: typeof AppOrganizationNameProjectsNewRoute
  AppOrganizationNameActivitiesIndexRoute: typeof AppOrganizationNameActivitiesIndexRoute
  AppOrganizationNameConfigurationIndexRoute: typeof AppOrganizationNameConfigurationIndexRoute
  AppOrganizationNameProjectsIndexRoute: typeof AppOrganizationNameProjectsIndexRoute
}

const AppOrganizationNameRouteRouteChildren: AppOrganizationNameRouteRouteChildren =
  {
    AppOrganizationNameMembersRouteRoute:
      AppOrganizationNameMembersRouteRouteWithChildren,
    AppOrganizationNameIndexRoute: AppOrganizationNameIndexRoute,
    AppOrganizationNameProjectsIdRouteRoute:
      AppOrganizationNameProjectsIdRouteRouteWithChildren,
    AppOrganizationNameConfigurationActivitiesRoute:
      AppOrganizationNameConfigurationActivitiesRoute,
    AppOrganizationNameConfigurationDeleteRoute:
      AppOrganizationNameConfigurationDeleteRoute,
    AppOrganizationNameConfigurationDisplayNameRoute:
      AppOrganizationNameConfigurationDisplayNameRoute,
    AppOrganizationNameConfigurationExportRoute:
      AppOrganizationNameConfigurationExportRoute,
    AppOrganizationNameConfigurationImportRoute:
      AppOrganizationNameConfigurationImportRoute,
    AppOrganizationNameConfigurationNameRoute:
      AppOrganizationNameConfigurationNameRoute,
    AppOrganizationNameProjectsNewRoute: AppOrganizationNameProjectsNewRoute,
    AppOrganizationNameActivitiesIndexRoute:
      AppOrganizationNameActivitiesIndexRoute,
    AppOrganizationNameConfigurationIndexRoute:
      AppOrganizationNameConfigurationIndexRoute,
    AppOrganizationNameProjectsIndexRoute:
      AppOrganizationNameProjectsIndexRoute,
  }

const AppOrganizationNameRouteRouteWithChildren =
  AppOrganizationNameRouteRoute._addFileChildren(
    AppOrganizationNameRouteRouteChildren,
  )

interface AppRouteChildren {
  AppOrganizationNameRouteRoute: typeof AppOrganizationNameRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppMeDeleteRoute: typeof AppMeDeleteRoute
  AppMeEmailRoute: typeof AppMeEmailRoute
  AppMeIconRoute: typeof AppMeIconRoute
  AppMeInitializeRoute: typeof AppMeInitializeRoute
  AppMeNameRoute: typeof AppMeNameRoute
  AppMePasswordRoute: typeof AppMePasswordRoute
  AppOrganizationsNewRoute: typeof AppOrganizationsNewRoute
  AppMeIndexRoute: typeof AppMeIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrganizationNameRouteRoute: AppOrganizationNameRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppMeDeleteRoute: AppMeDeleteRoute,
  AppMeEmailRoute: AppMeEmailRoute,
  AppMeIconRoute: AppMeIconRoute,
  AppMeInitializeRoute: AppMeInitializeRoute,
  AppMeNameRoute: AppMeNameRoute,
  AppMePasswordRoute: AppMePasswordRoute,
  AppOrganizationsNewRoute: AppOrganizationsNewRoute,
  AppMeIndexRoute: AppMeIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InitializeRoute: InitializeRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
